# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afa1563ab185c7d2173aaa46654d0a4dac7e0a163cf3af255b26f089bc77d12a839252176edb0e88b511e6bc683bd799e7ee7fa75bb78cb1b5f692f6fe37d3a5

test:
  secret_key_base: ec33092734534a5e8d1e50a207183eae83cc6d60489446fe6ad4bdcdc9029aa3fd8422133e1a5990d6c24f6eb44e9f9c03c69862b58d20a763e93d72b2e6af70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
